src/NS/SentinelBundle/Entity/IBD/ExternalLab.php
<?php

namespace NS\SentinelBundle\Entity\IBD;

use Doctrine\ORM\Mapping as ORM;
use JMS\Serializer\Annotation as Serializer;
use NS\SecurityBundle\Annotation\Secured;
use NS\SecurityBundle\Annotation\SecuredCondition;
use NS\SentinelBundle\Entity\BaseExternalLab;
use NS\SentinelBundle\Form\IBD\Types\FinalResult;
use NS\SentinelBundle\Form\IBD\Types\HiSerotype;
use NS\SentinelBundle\Form\IBD\Types\IsolateType;
use NS\SentinelBundle\Form\IBD\Types\IsolateViable;
use NS\SentinelBundle\Form\IBD\Types\NmSerogroup;
use NS\SentinelBundle\Form\IBD\Types\PathogenIdentifier;
use NS\SentinelBundle\Form\IBD\Types\SampleType;
use NS\SentinelBundle\Form\IBD\Types\SerotypeIdentifier;
use NS\SentinelBundle\Form\IBD\Types\SpnSerotype;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Validator\Context\ExecutionContextInterface;

/**
 * Description of ExternalLab
 * @author gnat
 *
 * @Secured(conditions={
 *      @SecuredCondition(roles={"ROLE_REGION"},through={"caseFile"},relation="region",class="NSSentinelBundle:Region"),
 *      @SecuredCondition(roles={"ROLE_COUNTRY","ROLE_RRL_LAB","ROLE_NL_LAB"},through={"caseFile"},relation="country",class="NSSentinelBundle:Country"),
 *      @SecuredCondition(roles={"ROLE_SITE","ROLE_LAB"},through={"caseFile"},relation="site",class="NSSentinelBundle:Site"),
 *      })
 * @SuppressWarnings(PHPMD.LongVariable)
 * @ORM\MappedSuperclass
 */
abstract class ExternalLab extends BaseExternalLab
{
    /**
     * @var SampleType
     * @ORM\Column(name="type_sample_recd",type="SampleType",nullable=true)
     * @Serializer\Groups({"api","export"})
     */
    protected $type_sample_recd;

    /**
     * @var IsolateViable
     * @ORM\Column(name="isolate_viable",type="IsolateViable",nullable=true)
     * @Serializer\Groups({"api","export"})
     */
    protected $isolate_viable;

    /**
     * @var IsolateType
     * @ORM\Column(name="isolate_type",type="IsolateType",nullable=true)
     * @Serializer\Groups({"api","export"})
     */
    protected $isolate_type;

    /**
     * @var PathogenIdentifier
     * @ORM\Column(name="method_used_pathogen_identify",type="PathogenIdentifier",nullable=true)
     * @Serializer\Groups({"api","export"})
     */
    protected $method_used_pathogen_identify;

    /**
     * @var string
     * @ORM\Column(name="method_used_pathogen_identify_other", type="string",nullable=true)
     * @Serializer\Groups({"api","export"})
     */
    protected $method_used_pathogen_identify_other;

    /**
     * @var SerotypeIdentifier
     * @ORM\Column(name="method_used_st_sg",type="SerotypeIdentifier",nullable=true)
     * @Serializer\Groups({"api","export"})
     */
    protected $method_used_st_sg;

    /**
     * @var string
     * @ORM\Column(name="method_used_st_sg_other",type="string",nullable=true)
     * @Serializer\Groups({"api","export"})
     */
    protected $method_used_st_sg_other;

    /**
     * @var double
     * @ORM\Column(name="Spn_lytA",type="decimal",precision=3, scale=1,nullable=true)
     * @Assert\Range(min=-10,max=50)
     * @Serializer\Groups({"api","export"})
     */
    protected $spn_lytA;

    /**
     * @var integer $ctrA
     * @ORM\Column(name="Nm_ctrA",type="decimal",precision=3, scale=1,nullable=true)
     * @Assert\Range(min=-10,max=50)
     * @Serializer\Groups({"api","export"})
     */
    protected $nm_ctrA;

    /**
     * @var double
     * @ORM\Column(name="nm_sodC",type="decimal",precision=3, scale=1,nullable=true)
     * @Assert\Range(min=-10,max=50)
     * @Serializer\Groups({"api","export"})
     */
    protected $nm_sodC;

    /**
     * @var double
     * @ORM\Column(name="hi_hpd1",type="decimal",precision=3, scale=1,nullable=true)
     * @Assert\Range(min=-10,max=50)
     * @Serializer\Groups({"api","export"})
     */
    protected $hi_hpd1;

    /**
     * @var double
     * @ORM\Column(name="hi_hpd3",type="decimal",precision=3, scale=1,nullable=true)
     * @Assert\Range(min=-10,max=50)
     * @Serializer\Groups({"api","export"})
     */
    protected $hi_hpd3;

    /**
     * @var double
     * @ORM\Column(name="hi_bexA",type="decimal",precision=3, scale=1,nullable=true)
     * @Assert\Range(min=-10,max=50)
     * @Serializer\Groups({"api","export"})
     */
    protected $hi_bexA;

    /**
     * @var double
     * @ORM\Column(name="humanDNA_RNAseP",type="decimal",precision=3, scale=1,nullable=true)
     * @Assert\Range(min=-10,max=50)
     * @Serializer\Groups({"api","export"})
     */
    protected $humanDNA_RNAseP;

    /**
     * @var FinalResult $finalResult
     * @ORM\Column(name="final_RL_result_detection",type="FinalResult",nullable=true)
     */
    protected $final_RL_result_detection;

    /**
     * @var SpnSerotype
     * @ORM\Column(name="spn_serotype",type="SpnSerotype",nullable=true)
     * @Serializer\Groups({"api","export"})
     */
    protected $spn_serotype;

    /**
     * @var HiSerotype
     * @ORM\Column(name="hi_serotype",type="HiSerotype",nullable=true)
     * @Serializer\Groups({"api","export"})
     */
    protected $hi_serotype;

    /**
     * @var NmSerogroup
     * @ORM\Column(name="nm_serogroup",type="NmSerogroup",nullable=true)
     * @Serializer\Groups({"api","export"})
     */
    protected $nm_serogroup;


    /**
     * @return SampleType
     */
    public function getSampleType()
    {
        return $this->type_sample_recd;
    }

    /**
     * @return IsolateViable
     */
    public function getIsolateViable()
    {
        return $this->isolate_viable;
    }

    /**
     * @return IsolateType
     */
    public function getIsolateType()
    {
        return $this->isolate_type;
    }

    /**
     * @return PathogenIdentifier
     */
    public function getPathogenIdentifierMethod()
    {
        return $this->method_used_pathogen_identify;
    }

    /**
     * @return string
     */
    public function getPathogenIdentifierOther()
    {
        return $this->method_used_pathogen_identify_other;
    }

    /**
     * @return SerotypeIdentifier
     */
    public function getSerotypeIdentifier()
    {
        return $this->method_used_st_sg;
    }

    /**
     * @return string
     */
    public function getSerotypeIdentifierOther()
    {
        return $this->method_used_st_sg_other;
    }

    /**
     * @return float
     */
    public function getLytA()
    {
        return $this->spn_lytA;
    }

    /**
     * @return int
     */
    public function getCtrA()
    {
        return $this->nm_ctrA;
    }

    /**
     * @return float
     */
    public function getSodC()
    {
        return $this->nm_sodC;
    }

    /**
     * @return float
     */
    public function getHpd1()
    {
        return $this->hi_hpd1;
    }

    /**
     * @return float
     */
    public function getHpd3()
    {
        return $this->hi_hpd3;
    }

    /**
     * @return float
     */
    public function getBexA()
    {
        return $this->hi_bexA;
    }

    /**
     * @return float
     */
    public function getRNaseP()
    {
        return $this->humanDNA_RNAseP;
    }

    /**
     * @return SpnSerotype
     */
    public function getSpnSerotype()
    {
        return $this->spn_serotype;
    }

    /**
     * @return HiSerotype
     */
    public function getHiSerotype()
    {
        return $this->hi_serotype;
    }

    /**
     * @return NmSerogroup
     */
    public function getNmSerogroup()
    {
        return $this->nm_serogroup;
    }

    /**
     * @param SampleType $sampleType
     */
    public function setSampleType(SampleType $sampleType)
    {
        $this->type_sample_recd = $sampleType;
    }

    /**
     * @param IsolateViable $isolateViable
     */
    public function setIsolateViable(IsolateViable $isolateViable)
    {
        $this->isolate_viable = $isolateViable;
    }

    /**
     * @param IsolateType $isolateType
     */
    public function setIsolateType(IsolateType $isolateType)
    {
        $this->isolate_type = $isolateType;
    }

    /**
     * @param PathogenIdentifier $pathogenIdentifierMethod
     */
    public function setPathogenIdentifierMethod(PathogenIdentifier $pathogenIdentifierMethod)
    {
        $this->method_used_pathogen_identify = $pathogenIdentifierMethod;
    }

    /**
     * @param $pathogenIdentifierOther
     */
    public function setPathogenIdentifierOther($pathogenIdentifierOther)
    {
        $this->method_used_pathogen_identify_other = $pathogenIdentifierOther;
    }

    /**
     * @param SerotypeIdentifier $serotypeIdentifier
     */
    public function setSerotypeIdentifier(SerotypeIdentifier $serotypeIdentifier)
    {
        $this->method_used_st_sg = $serotypeIdentifier;
    }

    /**
     * @param $serotypeIdentifierOther
     */
    public function setSerotypeIdentifierOther($serotypeIdentifierOther)
    {
        $this->method_used_st_sg_other = $serotypeIdentifierOther;
    }

    /**
     * @param $lytA
     */
    public function setLytA($lytA)
    {
        $this->spn_lytA = $lytA;
    }

    /**
     * @param $ctrA
     */
    public function setCtrA($ctrA)
    {
        $this->nm_ctrA = $ctrA;
    }

    /**
     * @param $sodC
     */
    public function setSodC($sodC)
    {
        $this->nm_sodC = $sodC;
    }

    /**
     * @param $hpd1
     */
    public function setHpd1($hpd1)
    {
        $this->hi_hpd1 = $hpd1;
    }

    /**
     * @param $hpd3
     */
    public function setHpd3($hpd3)
    {
        $this->hi_hpd3 = $hpd3;
    }

    /**
     * @param $bexA
     */
    public function setBexA($bexA)
    {
        $this->hi_bexA = $bexA;
    }

    /**
     * @param $rNaseP
     */
    public function setRNaseP($rNaseP)
    {
        $this->humanDNA_RNAseP = $rNaseP;
    }

    /**
     * @param SpnSerotype $spnSerotype
     */
    public function setSpnSerotype(SpnSerotype $spnSerotype = null)
    {
        $this->spn_serotype = $spnSerotype;
    }

    /**
     * @param HiSerotype $hiSerotype
     */

src/NS/SentinelBundle/Entity/IBD/NationalLab.php
<?php

namespace NS\SentinelBundle\Entity\IBD;

use DateTime;
use Doctrine\ORM\Mapping as ORM;
use JMS\Serializer\Annotation as Serializer;
use NS\SentinelBundle\Validators as LocalAssert;

/**
 * Description of ReferenceLab
 * @author gnat
 *
 * @ORM\Entity(repositoryClass="NS\SentinelBundle\Repository\IBD\NationalLabRepository")
 * @ORM\Table(name="ibd_national_labs")
 * @ORM\HasLifecycleCallbacks
 */
class NationalLab extends ExternalLab
{
    /**
     * @ORM\OneToOne(targetEntity="\NS\SentinelBundle\Entity\IBD",inversedBy="nationalLab")
     * @ORM\JoinColumn(nullable=false,onDelete="CASCADE")
     * @ORM\Id
     */
    protected $caseFile;

    /**
     * @var boolean
     * @ORM\Column(name="rl_isol_csf_sent",type="boolean",nullable=true)
     *
     * @LocalAssert\NoFutureDate()
     * @Serializer\Groups({"api","export"})
     */
    private $rl_isol_csf_sent;

    /**
     * @var DateTime
     * @ORM\Column(name="rl_isol_csf_date",type="date",nullable=true)
     *
     * @LocalAssert\NoFutureDate()
     * @Serializer\Groups({"api","export"})
     * @Serializer\Type(name="DateTime<'Y-m-d'>")
     */
    private $rl_isol_csf_date;

    /**
     * @var boolean
     * @ORM\Column(name="rl_isol_blood_sent",type="boolean",nullable=true)
     *
     * @LocalAssert\NoFutureDate()
     * @Serializer\Groups({"api","export"})
     */
    private $rl_isol_blood_sent;

    /**
     * @var DateTime
     * @ORM\Column(name="rl_isol_blood_date",type="date",nullable=true)
     *
     * @LocalAssert\NoFutureDate()
     * @Serializer\Groups({"api","export"})
     * @Serializer\Type(name="DateTime<'Y-m-d'>")
     */
    private $rl_isol_blood_date;

    /**
     * @var boolean
     * @ORM\Column(name="rl_other_sent",type="boolean",nullable=true)
     *
     * @LocalAssert\NoFutureDate()
     * @Serializer\Groups({"api","export"})
     */
    private $rl_other_sent;

    /**
     * @var DateTime
     * @ORM\Column(name="rl_other_date",type="date",nullable=true)
     *
     * @LocalAssert\NoFutureDate()
     * @Serializer\Groups({"api","export"})
     * @Serializer\Type(name="DateTime<'Y-m-d'>")
     */
    private $rl_other_date;

    /**
     * @var string
     */
    private $type        = 'NL';

    /**
     * @return string
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * @param $type
     * @return $this
     */
    public function setType($type)
    {
        $this->type = $type;
        return $this;
    }

    /**
     * @return bool
     */
    public function isRlIsolCsfSent()
    {
        return $this->rl_isol_csf_sent;
    }

    /**
     * @param bool $rl_isol_csf_sent
     */
    public function setRlIsolCsfSent($rl_isol_csf_sent)
    {
        $this->rl_isol_csf_sent = $rl_isol_csf_sent;
    }

    /**
     * @return DateTime
     */
    public function getRlIsolCsfDate()
    {
        return $this->rl_isol_csf_date;
    }

    /**
     * @param DateTime $rl_isol_csf_date
     */
    public function setRlIsolCsfDate(DateTime $rl_isol_csf_date = null)
    {
        $this->rl_isol_csf_date = $rl_isol_csf_date;
    }

    /**
     * @return bool
     */
    public function isRlIsolBloodSent()
    {
        return $this->rl_isol_blood_sent;
    }

    /**
     * @param bool $rl_isol_blood_sent
     */
    public function setRlIsolBloodSent($rl_isol_blood_sent)
    {
        $this->rl_isol_blood_sent = $rl_isol_blood_sent;
    }

    /**
     * @return DateTime
     */
    public function getRlIsolBloodDate()
    {
        return $this->rl_isol_blood_date;
    }

    /**
     * @param DateTime $rl_isol_blood_date
     */
    public function setRlIsolBloodDate(DateTime $rl_isol_blood_date = null)
    {
        $this->rl_isol_blood_date = $rl_isol_blood_date;
    }

    /**
     * @return bool
     */
    public function isRlOtherSent()
    {
        return $this->rl_other_sent;
    }

    /**
     * @param bool $rl_other_sent
     */
    public function setRlOtherSent($rl_other_sent)
    {
        $this->rl_other_sent = $rl_other_sent;
    }

    /**
     * @return DateTime
     */
    public function getRlOtherDate()
    {
        return $this->rl_other_date;
    }

    /**
     * @param DateTime $rl_other_date
     */
    public function setRlOtherDate(DateTime $rl_other_date = null)
    {
        $this->rl_other_date = $rl_other_date;
    }

    /**
     * @return bool
     */
    public function getSentToReferenceLab()
    {
        return ($this->rl_isol_csf_sent || $this->rl_isol_blood_sent || $this->rl_other_sent);
    }
}

src/NS/SentinelBundle/Entity/IBD/ReferenceLab.php
<?php

namespace NS\SentinelBundle\Entity\IBD;

use Doctrine\ORM\Mapping as ORM;
use NS\SentinelBundle\Entity\ReferenceLab as RegionalReferenceLab;
use NS\SentinelBundle\Entity\ReferenceLabResultInterface;

/**
 * Description of ReferenceLab
 * @author gnat
 *
 * @ORM\Entity(repositoryClass="NS\SentinelBundle\Repository\IBD\ReferenceLabRepository")
 * @ORM\Table(name="ibd_reference_labs")
 * @ORM\HasLifecycleCallbacks
 */
class ReferenceLab extends ExternalLab implements ReferenceLabResultInterface
{
    /**
     * @ORM\OneToOne(targetEntity="\NS\SentinelBundle\Entity\IBD",inversedBy="referenceLab")
     * @ORM\JoinColumn(nullable=false,onDelete="CASCADE")
     * @ORM\Id
     */
    protected $caseFile;

    /**
     * @var RegionalReferenceLab $lab
     * @ORM\ManyToOne(targetEntity="NS\SentinelBundle\Entity\ReferenceLab",inversedBy="ibdCases")
     * @ORM\JoinColumn(name="rrl_id")
     */
    private $lab;

    /** @var string */
    private $type = 'RRL';

    public function getLab(): ?RegionalReferenceLab
    {
        return $this->lab;
    }

    public function setLab(?RegionalReferenceLab $lab): void
    {
        $this->lab = $lab;
    }

    public function getType(): string
    {
        return $this->type;
    }
}

src/NS/SentinelBundle/Entity/IBD/Types/BinaxResult.php
<?php

namespace NS\SentinelBundle\Entity\IBD\Types;

use NS\UtilBundle\Entity\Types\ArrayChoice;

/**
 * Class BinaxResult
 * @package NS\SentinelBundle\Entity\IBD\Types
 */
class BinaxResult extends ArrayChoice
{
    /**
     * @var string
     */
    protected $convert_class = 'NS\SentinelBundle\Form\IBD\Types\BinaxResult';

    /**
     * @return string
     */
    public function getName()
    {
        return 'BinaxResult';
    }
}

src/NS/SentinelBundle/Entity/IBD/Types/CSFAppearance.php
<?php

namespace NS\SentinelBundle\Entity\IBD\Types;

use NS\UtilBundle\Entity\Types\ArrayChoice;

/**
 * Description of TripleChoice
 * TODO remove once all live and ibd_cases table has been deleted
 *
 * @author gnat
 */
class CSFAppearance extends ArrayChoice
{
    /**
     * @var string
     */
    protected $convert_class = '\NS\SentinelBundle\Form\IBD\Types\CSFAppearance';

    /**
     * @return string
     */
    public function getName()
    {
        return 'CSFAppearance';
    }
}

src/NS/SentinelBundle/Entity/IBD/Types/CXRAdditionalResult.php
<?php

namespace NS\SentinelBundle\Entity\IBD\Types;

use NS\UtilBundle\Entity\Types\ArrayChoice;

/**
 * Class CXRAdditionalResult
 * TODO remove once all live and ibd_cases table has been deleted
 *
 * @package NS\SentinelBundle\Entity\IBD\Types
 */
class CXRAdditionalResult extends ArrayChoice
{
    /**
     * @var string
     */
    protected $convert_class = 'NS\SentinelBundle\Form\IBD\Types\CXRAdditionalResult';

    /**
     * @return string
     */
    public function getName()
    {
        return 'CXRAdditionalResult';
    }
}

src/NS/SentinelBundle/Entity/IBD/Types/GramStain.php
<?php

namespace NS\SentinelBundle\Entity\IBD\Types;

use NS\UtilBundle\Entity\Types\ArrayChoice;
use NS\SentinelBundle\Form\IBD\Types\GramStain as FormType;

class GramStain extends ArrayChoice
{
    /** @var string */
    protected $convert_class = FormType::class;

    public function getName(): string
    {
        return 'GramStain';
    }
}

src/NS/SentinelBundle/Resources/views/IBD/editBaseLab.html.twig
{% extends "NSSentinelBundle::edit.html.twig" %}

{% block pagetitle %}
    {{'Edit %type% For Case %id%'|trans({'%id%': record.caseId,'%type%': form.vars.value.type})}}
{% endblock %}

{%block pageactions %}
    <div class="pull-right">{{case_big_actions(record)}}</div>
{%endblock %}

{% block body %}
    {{ form_errors(form) }}
    {{ form_start(form,{'action': path(editRoute,{'id': id}),'attr':{'novalidate': 'novalidate'} }) }}
        <div class="row">
            <div class="col-sm-12">
                <div class="tabbable">
                    <ul class="nav nav-tabs padding-12 tab-color-blue background-blue" id="myTab4">
                        <li class="active"><a data-toggle="tab" href="#labinfo">{{'Lab Information'|trans}}</a></li>
                        <li><a data-toggle="tab" href="#sample">{{'Sample Information'|trans}}</a></li>
                        <li><a data-toggle="tab" href="#ctvalues">{{'CT Values From PCR'|trans}}</a></li>
                        <li><a data-toggle="tab" href="#serotype">{{'Serotype / Serogroup Results'|trans}}</a></li>
                    </ul>
                </div>
                <div class="tab-content">
                    <div id="labinfo" class="tab-pane active">
                        {{ form_row(form.labId) }}
                    </div>

                    <div id="sample" class="tab-pane">
                        <div class="row">
                            <div class="col-sm-6 col-md-6 col-lg-6">
                                {{ form_row(form.dateReceived) }}
                                {{ form_row(form.sampleType) }}
                            </div>
                            <div class="col-sm-6 col-md-6 col-lg-6">
                                {{ form_row(form.isolateViable) }}
                                {{ form_row(form.isolateType) }}
                            </div>
                        </div>
                        <hr/>
                        <div class="row">
                            <div class="col-sm-6">
                                {{ form_row(form.pathogenIdentifierMethod) }}
                                {{ form_row(form.pathogenIdentifierOther) }}
                            </div>
                            <div class="col-sm-6">
                                {{ form_row(form.serotypeIdentifier) }}
                                {{ form_row(form.serotypeIdentifierOther) }}
                            </div>
                        </div>
                        {% if form.rlIsolCsfSent is defined %}
                            <hr/>
                            <div class="row">
                                <div class="col-sm-4">
                                    {{ form_row(form.rlIsolCsfSent) }}
                                    {{ form_row(form.rlIsolCsfDate) }}
                                </div>
                                <div class="col-sm-4">
                                    {{ form_row(form.rlIsolBloodSent) }}
                                    {{ form_row(form.rlIsolBloodDate) }}
                                </div>
                                <div class="col-sm-4">
                                    {{ form_row(form.rlOtherSent) }}
                                    {{ form_row(form.rlOtherDate) }}
                                </div>
                            </div>
                        {% endif %}
                    </div>

                    <div id="ctvalues" class="tab-pane">
                        <div class="row">
                            <div class="col-sm-6 col-md-6 col-lg-6">
                                {{ form_row(form.lytA) }}
                                {{ form_row(form.ctrA) }}
                                {{ form_row(form.sodC) }}
                            </div>
                            <div class="col-sm-6 col-md-6 col-lg-6">
                                {{ form_row(form.hpd1) }}
                                {{ form_row(form.hpd3) }}
                                {{ form_row(form.bexA) }}
                                {{ form_row(form.rNaseP) }}
                            </div>
                        </div>
                    </div>

                    <div id="serotype" class="tab-pane">
                        <div class="row">
                            <div class="col-md-6">
                                {{ form_row(form.finalResult) }}
                                {{ form_row(form.comment) }}
                            </div>
                            <div class="col-md-6">
                                {{ form_row(form.spnSerotype) }}
                                {{ form_row(form.hiSerotype) }}
                                {{ form_row(form.nmSerogroup) }}
                            </div>
                        </div>
                    </div>
                </div>
                <div class="form-actions center">
                    <a href="{{path('ibdIndex')}}" class="btn btn-sm btn-danger">{{'Cancel'|trans}}</a>
                    <button type="submit" name="save" class="btn btn-sm btn-success">{{'Save'|trans}} <i class="fa fa-arrow-right fa fa-on-right bigger-110"></i></button>
                    <button type="submit" name="saveclose" class="btn btn-sm btn-success">{{'Save & Close'|trans}} <i class="fa fa-arrow-right fa fa-on-right bigger-110"></i></button>
                </div>
            </div>
            {{form_rest(form)}}
        </div>
    {{ form_end(form) }}
{% endblock %}

src/NS/SentinelBundle/Resources/views/IBD/editOutcome.html.twig
{% extends "NSSentinelBundle::edit.html.twig" %}

{% block pagetitle %}
    {{ 'Edit Case Outcome %id%'|trans({'%id%': record.caseId}) }}
{% endblock %}

{% block pageactions %}
    <div class="pull-right">{{ case_big_actions(record) }}</div>
{% endblock %}

{% block body %}
    {{ form_errors(form) }}
    {{ form_start(form, {'action': path('ibdOutcomeEdit',{'id':id}),'attr':{'novalidate': 'novalidate'} }) }}
        <div class="row">
            <div class="col-sm-12">
                <div class="tabbable">
                    <ul class="nav nav-tabs padding-12 tab-color-blue background-blue" id="myTab4">
                        <li class="active"><a data-toggle="tab" href="#outcome">{{ 'Outcome Data'|trans }}</a></li>
                    </ul>
                </div>
                <div class="tab-content">
                    <div id="outcome" class="tab-pane active">
                        {% include 'NSSentinelBundle:IBD:_outcome.html.twig' %}
                    </div>
                </div>
                <div class="form-actions center">
                    <a href="{{ path('ibdIndex') }}" class="btn btn-sm btn-danger">{{ 'Cancel'|trans }}</a>
                    <button type="submit" name="save" class="btn btn-sm btn-success">{{ 'Save'|trans }} <i class="fa fa-arrow-right fa fa-on-right bigger-110"></i></button>
                    <button type="submit" name="saveclose" class="btn btn-sm btn-success">{{ 'Save & Close'|trans }} <i class="fa fa-arrow-right fa fa-on-right bigger-110"></i></button>
                </div>
            </div>
        </div>
    {{ form_end(form) }}
{% endblock %}

src/NS/SentinelBundle/Resources/views/IBD/index.html.twig
{% extends "NSSentinelBundle::layout.html.twig" %}
{% block pagetitle %}{{'Recent Cases'|trans}}{%endblock %}
{% block pagedescription %}{{'Lists the last %count% IBD cases'|trans({'%count%':app.session.get('ibd.index.limit',10)})}}{%endblock %}

{% block javascripts %}
{{ parent() }}
    <script type="text/javascript" src="{{ asset('/bundles/nsfilteredpagination/js/main.js') }}"></script>
{% endblock %}

{% block body %}
    <div class="row">
        <div class="col-sm-9 col-md-9 col-lg-9">
            {% if is_granted('ROLE_CAN_CREATE') %}
                <div class="widget-box widget-color-blue">
                    <div class="widget-header widget-header-small">
                        <h5 class="widget-title">{{'Create/Edit Case'|trans}}</h5>
                    </div>
                    <div class="widget-body">
                        <form method="post" action="{{ path('ibdCreate') }}">
                            <div class="widget-main">
                                {{form_rest(createForm)}}
                            </div>
                            <div class="widget-toolbox padding-5 clearfix">
                                <button class="btn btn-sm btn-success pull-right"> {{ 'Create/Edit'|trans }}</button>
                            </div>
                        </form>
                    </div>
                </div>
            {% endif %}
            {% if pagination %}
                <div class="widget-box widget-color-blue no-border">
                    <div class="widget-header widget-header-small">
                        <h5 class="widget-title">{{'Latest IBD Cases'|trans}}</h5>
                        <div class="widget-toolbar">{{ form_widget(limitForm.limit) }} {{ 'Results per page'|trans }}</div>
                        <div class="widget-toolbar no-border">{{ knp_pagination_render(pagination) }}</div>
                    </div>
                    <div class="widget-body">
                        <div class="widget-main no-padding">
                            <div class="table">
                                {{ case_index_template(pagination,'ibdCases') }}
                            </div>
                        </div>
                    </div>
                </div>
            {% endif %}
        </div>
        <div class="col-xs-3 widget-container-span">
            {% include 'NSSentinelBundle::filter.html.twig' with {'route': 'ibdIndex'} %}
        </div>
    </div>
{% endblock %}